import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Providers from "./providers";
import Sidebar from "@/components/Sidebar";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={geistSans.variable}>
      <body className="bg-gray-100 text-gray-900 min-h-screen">
        <Providers>
          <Sidebar />
          <main className="ml-64 p-6">{children}</main>
        </Providers>
      </body>
    </html>
  );
}